name: Generate Clients

on:
  push:
    paths:
      - 'openapi.yaml'

jobs:
  generate-clients:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 (for Java clients)
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install OpenAPI Generator
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.2.0/openapi-generator-cli-6.2.0.jar -O openapi-generator-cli.jar

      # Generate Python Client
      - name: Generate Python Client
        run: |
          java -jar openapi-generator-cli.jar generate -i PagesServiceModel/openapi.yaml -g python -o ./generated/python-client

      # Push Generated Python Client to Repo
      - name: Push Python Client to PagesPythonClient Repo
        uses: stefanzweifel/push-action@v5
        with:
          directory: './generated/python-client'
          branch: main
          repository: Nadr0j/PagesPythonClient
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Generate Java Client
      - name: Generate Java Client
        run: |
          java -jar openapi-generator-cli.jar generate -i PagesServiceModel/openapi.yaml -g java -o ./generated/java-client

      # Push Generated Java Client to Repo
      - name: Push Java Client to PagesJavaClient Repo
        uses: stefanzweifel/push-action@v5
        with:
          directory: './generated/java-client'
          branch: main
          repository: Nadr0j/PagesJavaClient
          github_token: ${{ secrets.GITHUB_TOKEN }}
